// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRER4kWpdZ3E3PmNErwTy8w1IqJ5sPkrA',
    appId: '1:339546022024:web:a91dc960c2981321467f3d',
    messagingSenderId: '339546022024',
    projectId: 'kalorimatik',
    authDomain: 'kalorimatik.firebaseapp.com',
    storageBucket: 'kalorimatik.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4v-aa9XwHAQyghAyFvxjbdpdA0md4gH8',
    appId: '1:339546022024:android:90333ffe8a03d0f3467f3d',
    messagingSenderId: '339546022024',
    projectId: 'kalorimatik',
    storageBucket: 'kalorimatik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClvq6p53LGfhja_7gl3WNzV4EmjptQMds',
    appId: '1:339546022024:ios:5e998977890b2b09467f3d',
    messagingSenderId: '339546022024',
    projectId: 'kalorimatik',
    storageBucket: 'kalorimatik.appspot.com',
    iosBundleId: 'com.example.kalorimatik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClvq6p53LGfhja_7gl3WNzV4EmjptQMds',
    appId: '1:339546022024:ios:5e998977890b2b09467f3d',
    messagingSenderId: '339546022024',
    projectId: 'kalorimatik',
    storageBucket: 'kalorimatik.appspot.com',
    iosBundleId: 'com.example.kalorimatik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRER4kWpdZ3E3PmNErwTy8w1IqJ5sPkrA',
    appId: '1:339546022024:web:f8dfb138bf7b7999467f3d',
    messagingSenderId: '339546022024',
    projectId: 'kalorimatik',
    authDomain: 'kalorimatik.firebaseapp.com',
    storageBucket: 'kalorimatik.appspot.com',
  );

}